### ISSUE TITLE
[Request] Allow the "CTRL" (extra button) to be rebound in controls menu

### ISSUE THREAD

**Issue by aking4125** [Christofmeg/FastEntityTransfer#10]
Hello!

If possible if we could have the CTRL keybind to be reboundable? 

Some players are getting issues where interacting with the furnaces, blast furnaces, and smokers won't open the GUI or allow items to be interacted with as they have CTRL bound to sneak which they also set as a toggle and is causing weridness with it.

There doesn't seem to be a way to rebound the key in its current state (1.20.1)

**Comment by Christofmeg** [comment]
@aking4125 what version of the mod are you using? 

I can look into implementing a rebindable key for the ctrl feature.

**Comment by Christofmeg** [comment]
Implemented in version 1.3.1
