### ISSUE TITLE
[1.18.2] [Forge] Furnaces don't start smelting of fuel is inserted last.

### ISSUE THREAD

**Issue by V972** [Christofmeg/FastEntityTransfer#4]
Minecraft: 1.18.2
Forge: 40.2.0
Mod: fastentitytransfer-1.18.x-1.0.0

If smeltable items are inserted AFTER the fuel, everything works, but not the other way around.

**Comment by TheActOfTrying** [comment]
> Minecraft: 1.18.2 Forge: 40.2.0 Mod: fastentitytransfer-1.18.x-1.0.0
> 
> If smeltable items are inserted AFTER the fuel, everything works, but not the other way around.

Hi.
I'm looking into the issue.
Are you running any other mods?

**Comment by TheActOfTrying** [comment]
@V972

Hi.
I'm looking into the issue.
Are you running any other mods?

**Comment by V972** [comment]
A lot actually.
Don't wanna clutter it here, so here's a file: [modlist.txt](https://github.com/Christofmeg/FastEntityTransfer/files/10907549/modlist.txt)

**Comment by Christofmeg** [comment]
@V972
Can you export a copy of the pack you're using, so we can reproduce the issue?

**Comment by V972** [comment]
Sorry for the late reply, I didn't have electricity until yesterday.
[Here's the pack](https://drive.google.com/file/d/1_VHVQ2O41t68clVmjWSQl89U24dHarSb/view?usp=share_link) (Google Drive).
I am using vanilla launcher w/ instances.

**Comment by Christofmeg** [comment]
canary-mc1.18.2-0.1.6 was the perpetrator

**Comment by Christofmeg** [comment]
@V972 
To fix the issue add the following line to **canary.properties** in your config folder:
- mixin.world.block_entity_ticking.sleeping.furnace = false
