### ISSUE TITLE
[Forge - 1.19.2]: Tries to insert without using keybind

### ISSUE THREAD

**Issue by SiverDX** [Christofmeg/FastEntityTransfer#9]
**Version**: 1.2.1

Playing on a server, not sure if this also occurs in Singelplayer
But basically after I haven't interacted with the furnace for some time it (tries to) inserts my item into it
Even if I don't press Shift or Control

This only happens once and after that it's fine for a while

**Comment by Christofmeg** [comment]
Fixed in version 1.2.2
